### ISSUE TITLE
Change the twitter logo to 'X'

### ISSUE THREAD

**Issue by singodiyashubham87** [hfjooste/UltimateStarterKit#101]
The logo for twitter is still the old one, I want to replace it with the new updated one.
Kindly assign me this issue.

![image](https://github.com/hfjooste/UltimateStarterKit/assets/93720428/d4eb3ba1-632e-433b-92ca-f4a00a94f1a8)

**Comment by ParthMakode** [comment]
the icon is fetched from MkDocs itself so , we cannot change anything here on this repo

**Comment by singodiyashubham87** [comment]
@hfjooste Where is this mkdocs.yml file? Can you please guide me as I haven't worked with Mkdocs.

**Comment by hfjooste** [comment]
@singodiyashubham87 This file is in the root of the project (same directory as the README and uproject files). Just search for the Twitter stuff in there and change the icon to `x-twitter`

https://github.com/hfjooste/UltimateStarterKit/blob/main/mkdocs.yml
