### ISSUE TITLE
Change Twitter Logo

### ISSUE THREAD

**Issue by Vijaykv5** [hfjooste/UltimateStarterKit#107]
<img width="1424" alt="Screenshot 2023-10-28 at 10 13 23 AM" src="https://github.com/hfjooste/UltimateStarterKit/assets/94985341/736d8290-68be-4e36-b810-e6029fd6bc93">

change the twitter logo to X

**Comment by hfjooste** [comment]
This has already been changed. The website will be updated when the next build is released
