### ISSUE TITLE
 Camera Component is not attached to the Spring Arm Component in USKCharacter.

### ISSUE THREAD

**Issue by HeadClot** [hfjooste/UltimateStarterKit#125]
As the title says the Camera Component is not attached to the Spring Arm Component. This prevents quick and accurate adjustment of camera distance from the character. It also prevents collision tests between the character and the camera.

**Comment by hfjooste** [comment]
@HeadClot The camera component is attached to the Spring Arm Component at runtime depending on the camera perspective (only in 3rd person). I've tested the collision tests between character and camera. That is working in the demo project. Changing the camera distance is also possible (check the screenshot for the properties)

![image](https://github.com/hfjooste/UltimateStarterKit/assets/18502706/f766ae5a-fae5-4666-bfb5-d6b3db8f63ac)
![image](https://github.com/hfjooste/UltimateStarterKit/assets/18502706/a8ae68de-487c-48a6-a801-c53c614ac147)

**Comment by HeadClot** [comment]
Got it. Thank you for the info. I was a bit confused about this.
