### ISSUE TITLE
Create FPS character

### ISSUE THREAD

**Issue by hfjooste** [hfjooste/UltimateStarterKit#61]

**Comment by HeadClot** [comment]
A quick about this issue -
Is there a list of features that will be added to the FPS Character?

Also would it be possible to add a leaning and prone to the FPS Character?

**Comment by hfjooste** [comment]
I haven't really planned out the features for this. I'm going to start off by making the platformer character a bit more generic and reuse those features for the FPS character. So it will be a bit cartoony/casual with things like double jump, variable jump height and coyote time. Once that is done, I'll focus on adding more "serious" features. So far I'm thinking about adding crouch, prone, leaning and sliding (all without animations though since I'm not a 3D artist). After all these features are working, I'll start with some basic weapon systems

**Comment by hfjooste** [comment]
This is available in v3.5.0. More features will be added soon:

- https://github.com/hfjooste/UltimateStarterKit/issues/64 
- https://github.com/hfjooste/UltimateStarterKit/issues/65
- https://github.com/hfjooste/UltimateStarterKit/issues/66
- https://github.com/hfjooste/UltimateStarterKit/issues/67
- https://github.com/hfjooste/UltimateStarterKit/issues/68
- https://github.com/hfjooste/UltimateStarterKit/issues/69
- https://github.com/hfjooste/UltimateStarterKit/issues/70
- https://github.com/hfjooste/UltimateStarterKit/issues/71
- https://github.com/hfjooste/UltimateStarterKit/issues/72
