### ISSUE TITLE
Add proning to characters

### ISSUE THREAD

**Issue by hfjooste** [hfjooste/UltimateStarterKit#65]

**Comment by HeadClot** [comment]
Hey @hfjooste if you are stuck on this check out [Predicted Movement GitHub](https://github.com/Vaei/PredictedMovement)for how to do this. Hope this helps :)

**Comment by hfjooste** [comment]
Thanks @HeadClot. I'll check it out. I haven't really looked into adding this feature. I'm really busy other work/projects at the moment and don't have a lot of free time to work on this right now

**Comment by HeadClot** [comment]
Totally understandable.

**Comment by hfjooste** [comment]
This is available in v3.21.0
