### ISSUE TITLE
Error message missing modules - no work in 5.1

### ISSUE THREAD

**Issue by kisswdev2** [hfjooste/UltimateStarterKit#73]
Error message missing modules
the following module are missing or build with a different engine version
USK
USKEditor
Engine modules cannot be compiled at runtime.please build through you IDE

NO WORKINGG !!
HELP ME

**Comment by hfjooste** [comment]
Hey @kisswdev2 . Can you please provide more info?
1. Which version of the plugin are you using (including the UE version of the plugin)?
2. Did you add the plugin to the engine or project?
3. Are you using the latest version of UE 5.1 (5.1.1)?

I've tested it this morning by copying the plugin to the engine directory. I then made a new UE 5.1.1 project, enabled the plugin and everything worked. I've even tried to use some features from the plugin. I've only seen this issue before if you're using an older version of UE (e.g. UE 5.1 without the 5.1.1 update) or if you're using the wrong version of the plugin (e.g. using the UE 5.2 version of the plugin with UE 5.1)

![image](https://github.com/hfjooste/UltimateStarterKit/assets/18502706/761add8a-eb07-45b8-872b-8b31817beb1d)

**Comment by kisswdev2** [comment]
Hy yes i test yesterday i activate niagara but i dont have enchanted input
i put in folder plugins marketplace i open the ue5.1 and i got that error
when i open the project first person and tps  same error
